#!/usr/bin/env bash
ERRFILE="https://raw.github.com/postgres/postgres/master/src/backend/utils/errcodes.txt"
date=$(date)
echo "%% DO NOT EDIT - AUTOGENERATED ON $date"
wget -qO- "$ERRFILE" | ./convert_errcodes.txt.awk
